// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-YXPfiISbNC_AnsMQkst2ud4YY1TaeYo',
    appId: '1:325343096268:android:7f806c0c4aaf2aeabcc169',
    messagingSenderId: '325343096268',
    projectId: 'helpmetospeak-38686',
    storageBucket: 'helpmetospeak-38686.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Pdxf7-4FVOThas5sHU7xym2p8OVTpnI',
    appId: '1:325343096268:ios:57c27c4206c9d5d2bcc169',
    messagingSenderId: '325343096268',
    projectId: 'helpmetospeak-38686',
    storageBucket: 'helpmetospeak-38686.firebasestorage.app',
    androidClientId: '325343096268-gs4aof303ufedpb38po0tnm2su81f2l5.apps.googleusercontent.com',
    iosClientId: '325343096268-6d77nc84v4bks1blrjjal0k578avurnu.apps.googleusercontent.com',
    iosBundleId: 'com.minion.minionApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-YXPfiISbNC_AnsMQkst2ud4YY1TaeYo',
    appId: '1:325343096268:web:minion-web',
    messagingSenderId: '325343096268',
    projectId: 'helpmetospeak-38686',
    storageBucket: 'helpmetospeak-38686.firebasestorage.app',
    authDomain: 'helpmetospeak-38686.firebaseapp.com',
  );
}
